apiVersion: v1
kind: Service
metadata:
  name: aks-image-svc
  namespace: image
  labels:
    app: aks-image
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: aks-image