apiVersion: v1
kind: PersistentVolume
metadata:
  name: imagepv
  namespace: image
  labels: {
    container_type: store

  }
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: sc-image
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: image-pvc
    namespace: image
  azureFile:
    secretName: sa-secret
    secretNamespace: image
    shareName: imagefileshare
    readOnly: false