apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-image-deploy
  namespace: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-image
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: aks-image
    spec:
      containers:
      - name: aks-image-container
        image: prodrmspoc.azurecr.io/aks-main:199927-AKSMainV2
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 80
        env:
        - name: MyCustomPath.cutomepath
          valueFrom:
            configMapKeyRef:
              key: cutomepath
              name: configmap-image
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        volumeMounts:
        - name: imagepv
          mountPath: /imagefileshare
          subPath: share
      volumes:
      - name: imagepv
        persistentVolumeClaim:
          claimName: image-pvc